### ISSUE TITLE
Timeout Error

### ISSUE THREAD

**Issue by dale-courtney** [wandera/1password-client#31]
I can successfully run the following: 

_from onepassword import OnePassword
import json
op = OnePassword()_

I'm able to successfully input all of the requested info (email_address, domain_name, account_name, secret_key, password). 
I do have 2FA enabled, but I am not prompted for my 2FA. 

When I run the following: 

_json.loads(op.list_vaults())_

I get the following error every time: 

_Traceback (most recent call last):
  File "<input>", line 4, in <module>
  File "/usr/local/lib/python3.9/site-packages/onepassword/client.py", line 44, in __init__
    self.first_use()
  File "/usr/local/lib/python3.9/site-packages/onepassword/client.py", line 76, in first_use
    self.signin_wrapper(account, signin_domain, email_address, secret_key)
  File "/usr/local/lib/python3.9/site-packages/onepassword/client.py", line 103, in signin_wrapper
    password, session_key, domain, account, bp = self._signin(account, domain, email, secret_key, master_password)
  File "/usr/local/lib/python3.9/site-packages/onepassword/client.py", line 172, in _signin
    sess_key = _spawn_signin(op_command, master_password)
  File "/usr/local/lib/python3.9/site-packages/onepassword/utils.py", line 80, in _spawn_signin
    resp = child.expect(['Enter your six-digit authentication code:', pexpect.EOF])
  File "/usr/local/lib/python3.9/site-packages/pexpect/spawnbase.py", line 343, in expect
    return self.expect_list(compiled_pattern_list,
  File "/usr/local/lib/python3.9/site-packages/pexpect/spawnbase.py", line 372, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python3.9/site-packages/pexpect/expect.py", line 181, in expect_loop
    return self.timeout(e)
  File "/usr/local/lib/python3.9/site-packages/pexpect/expect.py", line 144, in timeout
    raise exc
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x10a0e23d0>
command: /usr/local/bin/op
args: ['/usr/local/bin/op', 'signin', 'domain', 'email_address', 'secret_key', '--raw', '--shorthand', 'name']
buffer (last 100 chars): b'in.\r\nEnter the Secret Key for email_address at signin_domain: '
before (last 100 chars): b'in.\r\nEnter the Secret Key for email_address at signin_domain: '
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 82848
child_fd: 8
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile(b'Enter your six-digit authentication code:')
    1: EOF_

**Comment by dtpryce** [comment]
A weird one since new release we have had a couple timeouts which are due to regex for master password not matching we think. Can you tell me the general format of the account and 1password domain you are using?

**Comment by dtpryce** [comment]
I just tested using 2FA in my personal machine (Mac M1) and in an ubuntu docker image using python 3.8. Nothing seemed to be wrong there. If you can share what values or even basic format of the email, domain and account you are trying to set. That can help us debug the issue with the regex plus tell us a little more about your environment so we can test the client including system, os, op --version and python --version. Thanks!

**Comment by dale-courtney** [comment]
- System: 1Password for Teams
- OS: macOS 11.4 on a MacBook Pro (2.4 GHz 8-Core Intel Core i9, 64 GB 2667 MHz DDR4)
- op version 1.10.3
- python 3.9.4 
- email: dale.courtney@economicmodeling.com

These are provided with yes/no choices: 
- domain (economicmodeling.1password.com)
- account name (economicmodeling)

Input: 

- secret key (standard 1Password secret key format)
- master password: this has two special characters: + and {, otherwise standard alphanumeric

Thanks for looking at this for me. 

Best,
Dale

**Comment by dale-courtney** [comment]
OK, call me stupid. 
When the script prompted me for the account name, I went with the default provided. But that's not actually the account name but the domain name. 
I'm so sorry for sending everyone on a wild goose chase.

**Comment by dtpryce** [comment]
Hahaha no worries! Glad it's working for you now! Could we make our docs or logging clearer?
