### ISSUE TITLE
No prompt for credentials, raise MissingCredentials() error returned

### ISSUE THREAD

**Issue by CommonGibbon** [wandera/1password-client#48]
**Describe the bug**
When I attempt to initialize onepassword using:
_op = OnePassword()_
I do not see a password prompt window and I receive a MissingCredentials error message

**To Reproduce**
_op = OnePassword()_

**Expected behavior**
I expect to see a window requesting my system password

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: firefox
 - Version: 22.04

Onepassword CLI version: 2.21.0
python verison: 3.10.12

This works as expected when running the cli from the command line (e.g. using op vault list). I believe this must be related to the cli version, because lines 137 and 138 in onepassword.py produce errors if I manually provide the OnePassword class with the dictionary of login values.

**Comment by CommonGibbon** [comment]
Well I figured it out. I guess I had used _pip3 install onepassword_ instead of _pip3 install 1password_. Sorry!

**Comment by dtpryce** [comment]
Hey @CommonGibbon thanks for submitting this issue ... if you are all good can we close it?
