### ISSUE TITLE
If a newer CLI version is present, the installer will try to overwrite it. 

### ISSUE THREAD

**Issue by costingalan** [wandera/1password-client#50]
**Describe the bug**
If a newer version is present, the installer will try to overwrite it. 

**To Reproduce**
1. Have a newer CLI version installed (currently, the code has 2.19.0)
2. Try to Install the client (via pip)

**Expected behavior**
Installation should succeed.

**Additional info**
Code is checking exact match: `if op == cli_version:`

**Comment by dtpryce** [comment]
Nice spot! One issue is that the cli isn't always backwards compatible and so we have to be careful when to install. I'll have a quick chat with the team and come back to you on your PR today.

**Comment by costingalan** [comment]
Thanks for the reply, @dtpryce ! I understand the reasoning. Maybe we can return a warning that the client hasn't been tested with the newer version and still let the user install the package.

**Comment by dtpryce** [comment]
Sorry I totally let this one slip!
