### ISSUE TITLE
Ability to use service accounts

### ISSUE THREAD

**Issue by RenewedMe** [wandera/1password-client#52]
**Is your feature request related to a problem? Please describe.**
In native linux I can use op as long as I have supplied a [service account](https://developer.1password.com/docs/service-accounts) token in the environment variable OP_SERVICE_ACCOUNT_TOKEN. However when I execute the following this is not enough to get me logged in and it asks me for a userid:
```
>>> from onepassword import OnePassword
>>> op = OnePassword()
Please input your 1Password account name e.g. wandera from wandera.1password.com: 
```

**Describe the solution you'd like**
I would like to see the same behaviour as I get when using the CLI: no need to sign in as the CLI will use the token in the environment variable to login

**Describe alternatives you've considered**
The alternative I considered is not using python but using a shell script to create a file to store the secrets I need

**Additional context**
n/a

**Comment by dtpryce** [comment]
Hey @RenewedMe thanks for the feature request. Since this is entirely new to us and not a workflow that we can easily test it might be a while but we shall endeavour to look into it!

**Comment by dtpryce** [comment]
@RenewedMe I believe we have added this feature now in 1.0.7 of the client.
After running `pip install 1password==1.0.7` make sure to read through our [readme here](https://github.com/wandera/1password-client#service-accounts) and follow all the setup steps (which I think you had already done, you might need to renew your token) and then try our client again.
