### ISSUE TITLE
1Password Python ERROR: Failed building wheel for 1password

### ISSUE THREAD

**Issue by jonmitten** [wandera/1password-client#53]
**Describe the bug**
Build environment:
MacOS Apple M2 Max
OS version 14.1.2 (23B92) Sonoma
1Password App at 1Password for Mac 8.10.20 (81020036)
1Password CLI installed via Homebrew at 2.23.0

When attempting to install 1Password Client for Python with `pip install 1password`, I receive the following error on my terminal:
```
      running install_scripts
      Downloading the 1Password CLI: op_apple_universal_v2.19.0.pkg
      error: [Errno 20] Not a directory: '/opt/homebrew/bin/op/op_apple_universal_v2.19.0.pkg8170fh4t.tmp'
      [end of output]
```
and indeed, attempting to navigate via `cd /opt/homebrew/bin/op` I get `cd: not a directory: /opt/homebrew/bin/op`

**To Reproduce**
With the same environment as above, do `pip install 1password`

**Expected behavior**
The package should install

**Desktop (please complete the following information):**
- MacOS Apple M2 Max
- OS version 14.1.2 (23B92) Sonoma
- 1Password App at 1Password for Mac 8.10.20 (81020036)
- 1Password CLI installed via Homebrew at 2.23.0

**Additional context**
I have upgraded all Homebrew packages, rebooted the computer.

**Comment by dtpryce** [comment]
This might be a version issue between us, MacOS and op. Will try to investigate next week and get back to you!

**Comment by dtpryce** [comment]
Hey @jonmitten ... I just tried a fresh install AFTER I bumped my `op` to 2.23.0 and all seems to work fine with 1.0.6 of our client. Can you try again (we just updated the code to be actually enable users to use higher versions of `op` at their own risk ;) ) - and just to be super sure use `pip install 1password==1.0.6`?

**Comment by jonmitten** [comment]
@dtpryce , using `pip install 1password==1.0.6` does indeed appear to have fixed the installation issue. Thank you!
