### ISSUE TITLE
Add support for `get_item`

### ISSUE THREAD

**Issue by mattnorris** [wandera/1password-client#9]
- `get_items` does not return the items' `details`. 
- `get_document` errs when trying to get an _item_: `<item> is not a document`. 

Am I overlooking something? Is there a way to get an item's `details`, which include the username and password? 

Thank you!

**Comment by dtpryce** [comment]
Thanks for raising! Will get this looked into, feel free to submit a PR also :)

**Comment by dtpryce** [comment]
@mattnorris we have just released a new version that covers:

* changed get_items to list_items to match the op functionality better
* added get_item that should allow you to get an item plus any drilled down fields 
* updated readme to show what is and isn't covered for any potential contributors out there 

Try it out and feel free to raise a new issue if that doesn't quite fit your use case!

**Comment by mattnorris** [comment]
@dtpryce you're fast! I came back here to start a PR. I was able to get it working by extending your class. 

I will check out the new version and let you know. Thanks!

**Comment by dtpryce** [comment]
No worries, we use it quite a lot so we don't mind small changes like this but definitely a lot of scope for extending to cover other areas that we don't use (yet).
